name: 'Frontend: PR'

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: ['*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-setup-thrift@v1
      # - uses: valitydev/action-frontend/setup@v1
      - uses: ./.github/actions/setup
        with:
          npm-not-ci: 'true'
      - name: Codegen
        run: npm run codegen
      - uses: ./.github/actions/publish
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          npm-version-tag: 'pr'
          pr-only-labeled: 'true'
