name: 'Frontend: PR 2'

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: ['*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-setup-thrift@v1
      - uses: valitydev/action-frontend/setup-install@v2
        with:
          npm-not-ci: 'true'
      - name: Codegen
        run: npm run codegen2
