name: 'Frontend: PR'

on:
  pull_request:
    branches: ['*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-setup-thrift@v1
      - uses: valitydev/action-frontend/setup@v1
      - run: npm i # protocols don't always update the package-lock.json, so installing from package.json
      - name: Codegen
        run: npm run codegen
